title: Neha Deshmukh
#logo: /assets/img/headshot_circle.png
description: Data Scientist
show_downloads: false
#theme: jekyll-theme-minimal
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
