title: Neha Deshmukh
description: Data Scientist
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
markdown: GFM


#theme: jekyll-theme-minimal
#remote_theme: pages-themes/cayman@v0.2.0
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one

